# Auto-generated by NB07. Research/backtest only.

SEED = 20260906
RESEARCH_ONLY = True
DEPLOYMENT_AUTHORIZED = False
LIVE_TRADING_AUTHORIZED = False

START_DATE = (2021, 1, 1)
END_DATE = (2025, 12, 31)
STARTING_CASH = 1_000_000
BENCHMARK = "SPY"

RESOLUTION = "DAILY"
DATA_NORMALIZATION = "ADJUSTED"
WARMUP_BARS = 80
TRAINING_LOOKBACK_BARS = 320
RETRAIN_FREQUENCY = "MONTHLY"
REBALANCE_FREQUENCY = "MONTHLY"

FEATURES = [
    "ret_1",
    "mom_5",
    "mom_20",
    "vol_20",
    "vol_60",
    "volume_z20",
    "dollar_volume_z20",
    "ma_ratio_20",
    "ma_ratio_50",
]

MODEL_FAMILIES = [
    "logistic_regression",
    "knn",
    "random_forest",
    "mlp",
    "linear_regression",
]
CHAMPION_SELECTION_RULE = (
    "highest chronological validation balanced accuracy; "
    "tie-break by predefined model-complexity order"
)

SIGNAL_MODE = "CROSS_SECTIONAL_LONG_SHORT"
LONG_FRACTION = 0.20
SHORT_FRACTION = 0.20
MIN_SIGNAL_ABS = 0.00

PORTFOLIO_METHOD = "inverse_volatility"
TARGET_DAILY_VOL = 0.010
MAX_GROSS = 1.00
MAX_POSITION_WEIGHT = 0.10
MAX_SECTOR_GROSS = 0.35
MAX_PORTFOLIO_DRAWDOWN = 0.12
EVENT_COOLDOWN_DAYS = 2

PER_ORDER_FEE_USD = 0.00
VOLUME_SHARE_LIMIT = 0.025
VOLUME_SHARE_PRICE_IMPACT = 0.10

UNIVERSE_BY_SECTOR = {
    "Technology": ["AAPL", "MSFT", "NVDA", "AVGO", "ORCL"],
    "Financials": ["JPM", "BAC", "GS", "MS", "C"],
    "Healthcare": ["JNJ", "UNH", "LLY", "MRK", "ABBV"],
    "Industrials": ["CAT", "GE", "HON", "UPS", "RTX"],
    "Consumer": ["AMZN", "WMT", "COST", "MCD", "HD"],
    "Energy": ["XOM", "CVX", "COP", "SLB", "EOG"],
}

AUDIT_OBJECT_STORE_KEY = "NB07/audit_bundle.json"
